name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

env:
  # electron-mocha needs this to run on Ubuntu - defines the X Server display to use
  DISPLAY: "$HOST_IP:0.0"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        include:
          - os: ubuntu-latest
            # https://github.com/jprichardson/electron-mocha/issues/186#issuecomment-873530087
            ubuntu-prefix: export DISPLAY=:45 && xvfb-run --server-num 45

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: ${{ matrix.ubuntu-prefix }} npm test
